### ISSUE TITLE
Unclear LICENSE: BSD / MIT

### ISSUE THREAD

**Issue by xhochy** [vmprof/vmprof-python#113]
The LICENSE file in the repository states that the project is MIT but the `setup.py` states that the package is BSD licensed. It would be nice to clear this up.

**Comment by planrich** [comment]
The LICENSE file really dictates the type of license. I guess that setup.py was generated/copied and nobody cared to change it. Are there any objections?

**Comment by fijal** [comment]
no, they're more or less the same
