### ISSUE TITLE
vmprof fails to install on Ubuntu 12.04, Python 2.7

### ISSUE THREAD

**Issue by claeyswo** [vmprof/vmprof-python#124]
[pip.txt](https://github.com/vmprof/vmprof-python/files/865176/pip.txt)

vmprof fails to install, pip error log attached above.

Thanks in advance.

**Comment by planrich** [comment]
Can you describe your system a little more. what I could figure out from the log:
* CPython 2.7
* Linunx 64 bit

How old is your GCC? Is there a reason why wheels are not used by your pip?

**Comment by planrich** [comment]
To summarize the issue a bit: vmprof includes libbacktrace maintained by gcc. It seems like the libbacktrace version was copied from a more recent version of gcc than ubuntu 12.04 ships.

The linux wheels from pypi should actually solve this issue. That is why I'm confused that pip does not use the prebuilt binary linux wheel.

**Comment by claeyswo** [comment]
Turns out we had an old version of pip, latest version seems to pick up the wheel.
Thank you!
