### ISSUE TITLE
MANIFEST.in missing dwarf2.def

### ISSUE THREAD

**Issue by anntzer** [vmprof/vmprof-python#128]
Currently, MANIFEST.in:
```
recursive-include src *.h *.c
include LICENSE
recursive-exclude vmprof/test *
recursive-exclude jitlog/test *
```
does not include (e.g.) src/libbacktrace/dwarf2.def, making the PyPI sdist incomplete:
```
$ pip install --no-binary=:all: vmprof
<elided>
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/usr/include/python3.6m -c src/libbacktrace/dwarf.c -o build/temp.linux-x86_64-3.6/src/libbacktrace/dwarf.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
    In file included from src/libbacktrace/dwarf.c:40:0:
    src/libbacktrace/dwarf2.h:75:22: fatal error: dwarf2.def: No such file or directory
     #include "dwarf2.def"
                          ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
error
<elided>
```
(Python 3.6.0 Arch Linux)

**Comment by planrich** [comment]
I have included all of libbacktrace in the source distribution. For now you should rather clone the git repo. There is still one issue for libbacktrace. On a 32-bit machine installing the source distribution one must run configure before the righ sources are generated. Can that be done in dist utils?

**Comment by anntzer** [comment]
Yes, you can e.g. override the `build_ext` command (https://github.com/anntzer/redeal/blob/master/setup.py#L41 and https://github.com/anntzer/redeal/blob/master/setup.py#L65 for something similar).

**Comment by planrich** [comment]
Ok, I have customized the build. This will be included in the next release!

**Comment by anntzer** [comment]
Do you know approximately when it will be?  Thanks!

**Comment by planrich** [comment]
I'm planning to implement #129 then I'll upload. Next or in two weeks? Is that too late?

**Comment by anntzer** [comment]
no worries, thanks!

**Comment by planrich** [comment]
0.4.4 is tagged and will be released soon!

**Comment by anntzer** [comment]
thanks!
