### ISSUE TITLE
vmprofshow errors when run

### ISSUE THREAD

**Issue by burtonwilliamt** [vmprof/vmprof-python#143]
Hi! I'm running pypy 5.1.2, and vmprof (0.4.6.dev1)
When I run
```
python -m vmprof -o profile.log solve.py
```
I get the error:
```
(pypy) root@ff95d4f3a727:~/app/testing3# vmprofshow profile.log
Traceback (most recent call last):
  File "/root/.virtualenvs/pypy/bin/vmprofshow", line 11, in <module>
    sys.exit(main())
  File "/root/.virtualenvs/pypy/site-packages/vmprof/show.py", line 263, in main
    pp.show(args.profile)
  File "/root/.virtualenvs/pypy/site-packages/vmprof/show.py", line 40, in show
    if stats.get_runtime_in_microseconds() < 1000000:
  File "/root/.virtualenvs/pypy/site-packages/vmprof/stats.py", line 33, in get_runtime_in_microseconds
    ts = self.end_time - self.start_time
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

The actual failure is on in [stats.py:33](https://github.com/vmprof/vmprof-python/blob/56a71e1dfb98b92caccac0620ae26e77c9d8b579/vmprof/stats.py#L33) but I found that isn't really the problem. Rather it's that the LogReaderState() function [reader.py:304](https://github.com/vmprof/vmprof-python/blob/56a71e1dfb98b92caccac0620ae26e77c9d8b579/vmprof/reader.py#L309-L310) returns a state that does not have a start or end time, which is supposed to be populated by the [read_all()](https://github.com/vmprof/vmprof-python/blob/56a71e1dfb98b92caccac0620ae26e77c9d8b579/vmprof/reader.py#L269) function, but for some reason mine is not doing that. I know that it's looking for a MARKER_TIME_N_ZONE in my log file which is '0x06' but I'm not sure where in the file it's expecting that to be so I'm not sure how to diagnose this further. Any help?

**Comment by planrich** [comment]
MARKER_TIME_N_ZONE is expected at the beginning (just before the first stack trace sample) and near the end. I think that PyPy 5.1.2 does not emit that marker (PyPy ships the implementation for vmprof on its own), which means it is simply to old.

Is it possible to upgrade?

**Comment by burtonwilliamt** [comment]
What version of PyPy should I be using?

**Comment by burtonwilliamt** [comment]
So I was running a docker image that had ubuntu 16.04 LTS, but I just updated the base container to 17.10 so that I could get the PyPy latest version 5.7.1 (16.04 didn't have a newer version of PyPy in the repos so I figured this was easier). I'm still using vmprof 0.4.6.dev1 and I'm getting the same issue.

**Comment by planrich** [comment]
That seems to be a real problem. Which docker image are you using? I'm trying to reproduce the issue.

**Comment by burtonwilliamt** [comment]
I'm using a custom image that I wrote a Dockerfile for

**Comment by planrich** [comment]
Ok, I'm trying to reproduce on the 'official' pypy docker image. It works here! Can I learn a little more about your setup? Could you maybe share the profile?

**Comment by burtonwilliamt** [comment]
Yeah, sure! I just had to remove he extraneous stuff I had and make sure that I still get the error. Sorry if it's gross, but for what I'm doing I need PyPy in a virtualenv on the docker, and the only way I can do that is by actually running /bin/bash stuff, not /bin/sh

```Dockerfile
FROM ubuntu:17.10

#install core components
RUN apt-get update \
  && yes | apt-get install\
  gcc-multilib\
  g++-multilib

#install tools
RUN yes | apt-get install\
  python-pip

#install mkvirtualenv
RUN yes | apt-get install virtualenv pypy pypy-dev&&\
  pip install --upgrade pip &&\
  pip install virtualenvwrapper


#add environment variables
#empty the ~/.profile because it recursively loaded ~/.bashrc when we soured it
RUN /bin/bash -c "echo \"\" > ~/.profile" &&\
  /bin/bash -c "echo \"export WORKON_HOME=$HOME/.virtualenvs\" >> ~/.profile" &&\
  /bin/bash -c "echo \"export PROJECT_HOME=$HOME/Devel\" >> ~/.profile" &&\
  /bin/bash -c "echo \"source /usr/local/bin/virtualenvwrapper.sh\" >> ~/.profile" &&\
  /bin/bash -c "source ~/.profile && mkvirtualenv --no-site-packages --distribute --python=/usr/bin/pypy pypy" &&\
  /bin/bash -c "echo \"source ~/.profile\" >> ~/.bashrc" &&\
  /bin/bash -c "echo \"workon pypy\" >> ~/.bashrc"


#install vmprof for statistical profiling in pypy
RUN /bin/bash -c "source ~/.profile && workon pypy && pip install vmprof==0.4.6.dev1"
```
Building with `docker build -t vmprof .`

And running with `docker run -it --rm -v "$PWD"/app:/root/app:rw -w /root/app vmprof /bin/bash`

**Comment by burtonwilliamt** [comment]
@planrich, did you ever get this to reproduce?

**Comment by planrich** [comment]
Yes I tried to, but failed to reproduce. What about newer versions? Does it still occur? I checked in a fix that does not crash vmprof for old PyPy versions.

**Comment by burtonwilliamt** [comment]
Ah, ok. It seems that the most recent version of vmprof (4.9.0) fixed this and other subsequent debugging issues for me. Thank you for your help!
