### ISSUE TITLE
ld: cannot find -lunwind-x86_64

### ISSUE THREAD

**Issue by nealmcb** [vmprof/vmprof-python#144]
when doing `pip install --user vmprof` I got these errors:
```
Downloading vmprof-0.4.5.tar.gz....
....
/usr/bin/ld: cannot find -lunwind
/usr/bin/ld: cannot find -lunwind-x86_64
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
In Ubuntu Trusty 14.04 LTS I had to install the dev version of `libunwind` to get it to build:

`sudo pip install libunwind8-dev`

This should probably be noted in the installation documentation.

**Comment by planrich** [comment]
The wheel ships the libunwind shared objects, this is really not wanted behaviour. Are you using CPython? Usually pip should pull the wheel version of vmprof, but I think that pip on 14.04 is rather old and tries to compile from source?

**Comment by nealmcb** [comment]
Good points. I think I was using the old version of pip (the standard version on Ubuntu Trusty: pip 1.5.4). I'm planning to run it with pypy, but pip would have been using CPython.

When trying to get vmprof running in a virtualenv with pypy, I was running in to other problems which I forget the details of now.  But as I recall, after installing in a virtualenv, when I ran with pypy I was getting complaints about not finding the library, perhaps because pypy was looking in different places for the libraries than where the virtualenv put them. And then when I made the virtualenv all about pypy, it couldn't download stuff because of that bug with SSL certificates. So I backed off to the vanilla 14.04 environments.  Complicated.....

**Comment by planrich** [comment]
I'm closing this for now. I have added a FAQ entry in the docs!

**Comment by nealmcb** [comment]
Thanks. I added a doc suggestion of my own, in case it's useful.

**Comment by JohnV7** [comment]
I do get the same error as nealmcb with pip 9.0.1 on ubuntu 16.04.. Any ideas?

**Comment by planrich** [comment]
I think this is related to #157

**Comment by openxxs** [comment]
I met the same problem when I try to install vmprof 0.4.12 in docker container of centos:7。Here is my solution:

1. `yum -y install libunwind.x86_64`
2. `pip install vmprof==0.4.12` failed: 
 `/usr/bin/ld: cannot find -lunwind`
 `/usr/bin/ld: cannot find -lunwind-x86_64`
3. `ls /lib64/libunwind*` shows me:
`/lib64/libunwind-coredump.so.0	/lib64/libunwind-coredump.so.0.0.0  /lib64/libunwind.so.8  /lib64/libunwind.so.8.0.1  /lib64/libunwind-x86_64.so.8	/lib64/libunwind-x86_64.so.8.0.1`
4. Rename libunwind.so.8-->libunwind.so and libunwind-x86_64.so.8--> libunwind-x86_64.so
5. Then `pip install vmprof==0.4.12` works fine >_<||
