### ISSUE TITLE
vmprofshow --filter could use some explanation, and maybe be different

### ISSUE THREAD

**Issue by boxed** [vmprof/vmprof-python#155]
When asking `vmprofshow --help` you get this:
```
  --filter FILTER
```

that's not very helpful! I read the code: https://github.com/vmprof/vmprof-python/blob/ca0c4e013acd885773b307d43d2ed8570ec16eb9/vmprof/show.py#L137 to find out what it does and it's not terribly useful of a filter. It won't let me target the path and that's what can separate my code from lib code. (Plus what's with "find" instead of "x in y"? :P )

**Comment by planrich** [comment]
I'm closing this for now. The commit will be release soon.
