### ISSUE TITLE
vmprof.com is down

### ISSUE THREAD

**Issue by ganwell** [vmprof/vmprof-python#190]
[It seems really down](http://downforeveryoneorjustme.com/vmprof.com)

Thanks for the great service!

**Comment by grigi** [comment]
Hi
vmprof.com is still down?

**Comment by cjw296** [comment]
I suspect it's gone for good: https://twitter.com/fijall/status/1128225067937275904

**Comment by fijal** [comment]
Sorry about that. I put it back up
