### ISSUE TITLE
"Connection refused" again

### ISSUE THREAD

**Issue by allefeld** [vmprof/vmprof-python#196]
With vmprof 0.4.12 under Python 3.7, Miniconda installation, Debian 9.9:

```
python -m vmprof.upload test.prof
Uploading to http://vmprof.com...
 => Uploading the cpu profile...
server rejected meta data. status: 400, msg: '["could not extract meta data for 9fb3440d-c769-4003-99aa-72adb3e729bc. exception: [Errno 111] Connection refused"]'
```

**Comment by kolypto** [comment]
Same issue here:

> Uploading to http://vmprof.com...
> => Uploading the cpu profile...
> server rejected meta data. status: 400, msg: '["could not extract meta data for c0198dd2-45aa-4465- a657-f66fbc3d85c4. exception: [Errno 111] Connection refused"]'

**Comment by Nitrooo** [comment]
+1
Same error.

**Comment by h-g-s** [comment]
+1

**Comment by HIRANO-Satoshi** [comment]
any workaround?

**Comment by LoHiaufung** [comment]
+1

**Comment by jay20162016** [comment]
You could run your own server

**Comment by mattip** [comment]
vmprof.com is no longer available. Please use the flame graph viewer https://pypy.org/posts/2024/05/vmprof-firefox-converter.html
