### ISSUE TITLE
Got "Segmentation fault: 11 " when profiling a PyPy + Flask + Gevent app

### ISSUE THREAD

**Issue by xqzhou** [vmprof/vmprof-python#224]
OS: Mac Catalina
Python: [PyPy 7.3.1 with GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)]
Gevent: 20.6.2

**Comment by mattip** [comment]
Can you try again with the recently released 0.4.17

**Comment by mattip** [comment]
Closing as this is stale.
