### ISSUE TITLE
"No module named _vmprof" error on Windows 10 x64 + pypy-jit latest nigthly

### ISSUE THREAD

**Issue by its5Q** [vmprof/vmprof-python#234]
I wanted to profile my script because it was 3 times slower running in PyPy than in python, and I ran into this issue. I installed vmprof and tried to run it with my script, but I got an error, here's the output:

```
# pypy3 -m vmprof --web preprocess_data.py

Traceback (most recent call last):
  File "...\pypy-c-jit-102448-3176908cd9d2-win64\lib-python\3\runpy.py", line 186, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "...\pypy-c-jit-102448-3176908cd9d2-win64\lib-python\3\runpy.py", line 145, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "...\pypy-c-jit-102448-3176908cd9d2-win64\lib-python\3\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "...\pypy-c-jit-102448-3176908cd9d2-win64\site-packages\vmprof\__init__.py", line 8, in <module>
    import _vmprof
ModuleNotFoundError: No module named '_vmprof'
```
Is it something with my installation or is the package broken? The only similar issue to that one is #24

**Comment by m1sterzer0** [comment]
i just hit this as well.

**Comment by mattip** [comment]
_vmprof is not enabled in the PyPy windows build. In the [line that disables it](https://foss.heptapod.net/pypy/pypy/-/blob/release-pypy2.7-v7.3.5/pypy/config/pypyoption.py#L76) there is the comment `# FIXME: missing details`.

**Comment by mattip** [comment]
Please file an issue on the [PyPy issue tracker](https://foss.heptapod.net/pypy/pypy/-/issues) with a minimal reproducer of the script that is slower on PyPy than on CPython.

**Comment by mattip** [comment]
Closing, the issue should be filed against PyPy.
