### ISSUE TITLE
Add wheel for Python3.7+

### ISSUE THREAD

**Issue by KimiNewt** [vmprof/vmprof-python#252]
Wheels are missing for newer Python versions. 

I wanted to use one in Python 3.7 that include libunwind (in a place where I can't `apt-get`). 

I couldn't see anything about how libunwind was packaged previously in `setup.py` or elsewhere, and I see it's simply placed in `.libs_vmprof` in previous version. If you could tell me how you packaged it I could maybe automate the process.

**Comment by ilanKeshet** [comment]
any updates on publishing new wheels?

**Comment by mattip** [comment]
We need to solve the windows segfault in tests to merge #257.

**Comment by ilanKeshet** [comment]
Hi @mattip, i see that #257 was merged 🥳 

Any room for optimism with regards to compiled wheels for python 3.9+?

**Comment by mattip** [comment]
I see the latest merge to master created wheels as artifacts [here](https://github.com/vmprof/vmprof-python/actions/runs/7278784473). Could you try downloading the artifact, unzipping it, and checking if those wheels work? If so I can upload them to PyPI

**Comment by ilanKeshet** [comment]
Sure, 

I've checked `vmprof-0.4.15-cp39-cp39-macosx_10_9_x86_64.whl` and `vmprof-0.4.15-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` and can report they are both working as expected. 

Specifically for the linux version, it works without requiring that i'd install libunwind-dev in the docker image  🥳 

@mattip Thank you so much for taking the time and looking into this issue 🙏 😄

**Comment by mattip** [comment]
Great. I added a tag 0.4.16 and will upload the artifacts once the wheels build.

**Comment by ilanKeshet** [comment]
Hi @mattip, noticed pypi hasn't yet been updated, anything i can do to help?

**Comment by mattip** [comment]
It turns out I cannot upload to PyPI. I have asked the current maintainers to upload the wheels.

**Comment by ilanKeshet** [comment]
Thank you 🙏

**Comment by mattip** [comment]
The 0.4.17 wheels are up. Closing.
