### ISSUE TITLE
vmprof.read_profile interface unpractical

### ISSUE THREAD

**Issue by kayhayen** [vmprof/vmprof-python#26]
Hello,

the interface "vmprof.read_profile" accepts a filename. It should accept a readable instead. When I meant to add a small header with start and end date, that wouldn't work without duplicating the code there that just opens the binary data there.

Yours,
Kay

**Comment by fijal** [comment]
I'm happy to accept a patch

**Comment by fijal** [comment]
Hi Kay.

Are you going to write a patch for it or should I close this issue?

**Comment by kayhayen** [comment]
Hello Maciej,

updating to vmprof latest and redoing my integration for Nuitka is high on
my list of
things to be done and for the next release cycle in February, where I want
to have
that comparison tool as a focus for that Nuitka release.

You can keep the issue open if you want, or I can create an issue on my
side, and
re-raise once there is actual code behind it.

Yours,
Kay



2016-01-18 10:52 GMT+01:00 Maciej Fijalkowski <notifications@github.com>:

**Comment by fijal** [comment]
Fixed by #69
