### ISSUE TITLE
Problem using FILE * and fileno with vmprof.disable

### ISSUE THREAD

**Issue by kayhayen** [vmprof/vmprof-python#27]
Hello,

interestingly the code worked like a charm with named temporary files from the tempfile module, but started to act up, once I use a FILE * on it.

I am getting this in the end, after seemingly vm.enable did its job.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/vmprof/__init__.py", line 52, in disable
    f = os.fdopen(os.dup(_prof_fileno), "rb")
OSError: [Errno 22] Invalid argument

The code I use is like this (excerpt):

    FILE *tempfile;
    tempfile = fopen("nuitka-performance.dat", "wb");

    PyObject *result = CALL_FUNCTION_WITH_ARGS2(
        PyObject_GetAttrString( vmprof_module, "enable"),
         PyInt_FromLong( fileno( tempfile ) ),
         PyFloat_FromDouble( 0.001 )
    );

and later:

    PyObject *result = CALL_FUNCTION_NO_ARGS(
        PyObject_GetAttrString( vmprof_module, "disable")
    );
    fclose( tempfile );

Is there anything that causes the fileno to go bad? I even tried to not close the file myself. I am now just ignoring any errors from disable as a workaround. But probably you are in fact expecting more than a file number, rather a Python object behind it at some place otherwise?

Yours,
Kay

**Comment by fijal** [comment]
We did merge a branch that avoids all the duping, can you try again? I'll close in the meantime, feel free to reopen
