### ISSUE TITLE
hotpatch code is derived from another project without a license

### ISSUE THREAD

**Issue by gpshead** [vmprof/vmprof-python#3]
src/hotpatch/elf.c has contents suggesting it wasn't written for this project.

A quick search reveals that it appears to have been derived from https://github.com/ice799/memprof/blob/master/ext/elf.c which has no open source license (and thus is effectively unusable unless that is resolved) - https://github.com/ice799/memprof/issues/19

**Comment by fijal** [comment]
https://twitter.com/joedamato/status/579183737667248129

I'll try to make him add the LICENSE to his project

**Comment by gpshead** [comment]
haha, thanks :)

**Comment by fijal** [comment]
done

**Comment by gpshead** [comment]
thanks!

pedantically you should probably include a copy of https://github.com/ice799/memprof/blob/master/LICENSE at the top of the files derived from that project and/or add it to your own licenses file.

**Comment by fijal** [comment]
I don't have to, since it's MIT :-P

but it's definitely nice for the authors to provide some reference. Feel
like making a pull request?
