### ISSUE TITLE
Docs describe non-existent vmprof.upload

### ISSUE THREAD

**Issue by jml** [vmprof/vmprof-python#30]
The [docs](https://vmprof.readthedocs.org/en/latest/) say:

> To upload an already saved profile log to the vmprof web server:
> `python -m vmprof.upload output.log`

However, when I try to run this I get the following:

```
$ python -m vmprof.upload flocker-control.vmprof
/home/ubuntu/.virtualenvs/flocker-dbg/bin/python: No module named vmprof.upload
```

I have `vmprof==0.1.4.2`

**Comment by fijal** [comment]
I uploaded a new version, should work although my knowledge of setup.py is minimal. I'll close it please reopen if the issue persists
