### ISSUE TITLE
vmprofshow fails to process file saved from vmprof

### ISSUE THREAD

**Issue by jml** [vmprof/vmprof-python#31]
I used vmprof to output profiling information for something that was running on a remote machine, in the hope of analyzing the file separately.

However, after running the process and gathering the data, when I try to view the file with `vmprofshow` I get an error:

```
$ vmprofshow flocker-control.vmprof
Fatal: could not read vmprof profile file 'flocker-control.vmprof': list index out of range
[52071 refs]
```

It should be noted that the original vmprof process segfaulted.

**Comment by fijal** [comment]
If the original process segfaulted then it surely can't work. As I said, I uploaded a new version that should not segfault, please retry
