### ISSUE TITLE
vmprof depends on Linux-specific tools

### ISSUE THREAD

**Issue by jml** [vmprof/vmprof-python#32]
My use case is that I want to profile something with vmprof on a remote server and then analyze it on my OS X laptop.

I can't do this with vmprof, because I can't install gelf.h and dwarf.h and so forth. I don't think any of these are necessary for analyzing profiling data, and so I don't see why I should need to install them. 

I guess the solution would be to split the package somehow.

**Comment by fijal** [comment]
Fixed with the revamp
