### ISSUE TITLE
Extension module must be linked with librt on Linux

### ISSUE THREAD

**Issue by borman** [vmprof/vmprof-python#4]
While trying out vmprof (git clone; python setup.py develop), I've ran into this (Ubuntu 12.04 x86_64):
```
% python -c 'import vmprof'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "vmprof/__init__.py", line 4, in <module>
    import _vmprof
ImportError: ./_vmprof.so: undefined symbol: clock_gettime
```
...which is due to `clock_gettime` being defined in librt.so

A simple patch
```diff
--- a/setup.py
+++ b/setup.py
@@ -20,7 +20,7 @@ else:
                                'src/vmprof.c',
                                ],
                             extra_compile_args=['-Wno-unused'],
-                            libraries=['elf', 'unwind'],
+                            libraries=['elf', 'unwind', 'rt'],
                             extra_link_args=['%s' % libdwarf])]
```
would fix the issue, though not in a portable way (at least some BSDs have this function defined in libc).

Not a pull request as I haven't found a clean&reliable way to do this yet (autotools folks [just test it](http://trac.mpich.org/projects/mpich/ticket/1013), but distutils does not seem to be flexible enough).

**Comment by fijal** [comment]
The manpage says "-lrt needed for libc before 2.17". Since I don't feel like adding logic for detecting libc version, I've added librt to be always included. Thanks for the report.
