### ISSUE TITLE
vmprofshow invalid arguments to `read_profile`

### ISSUE THREAD

**Issue by lkraider** [vmprof/vmprof-python#43]
vmprofshow is calling `read_profile` with additional arguments, causing an error:
```
Fatal: could not read vmprof profile file 'vmprof.log': read_profile() got an unexpected keyword argument 'virtual_only'
```
Call ([source](https://github.com/vmprof/vmprof-python/blob/1cf46cd95f04e8a35e08879f0a474f3e1ea13de4/vmprof/show.py#L42)):
```python
stats = vmprof.read_profile(profile, virtual_only=True, include_extra_info=True)
```

Signature ([source](https://github.com/vmprof/vmprof-python/blob/1cf46cd95f04e8a35e08879f0a474f3e1ea13de4/vmprof/profiler.py#L29)):
```python
def read_profile(prof_filename):
```

**Comment by fijal** [comment]
indeed vmprofshow is not tested at all and it's prone to breakage, I'll fix it tomorrow

**Comment by fijal** [comment]
Fixed. Sorry took so long, took the weekend a bit too seriously :-)

**Comment by lkraider** [comment]
The same issue happens on the `upload.py` file ([source](https://github.com/vmprof/vmprof-python/blob/cbd356630d396179341ccc2e6fe12281f58ae05a/vmprof/upload.py#L51)):

```python
    stats = vmprof.read_profile(profile, virtual_only=True)
```

**Comment by fijal** [comment]
fixed
