### ISSUE TITLE
please tag releases and include release notes

### ISSUE THREAD

**Issue by jab** [vmprof/vmprof-python#48]
Just noticed there was a new release of vmprof. Looked for a changelog under https://pypi.python.org/pypi/vmprof, https://vmprof.readthedocs.org/, and https://github.com/vmprof/vmprof-python, but didn't find any. Went to https://github.com/vmprof/vmprof-python/releases in hopes of seeing this info there, but came up empty since you're not tagging releases.

Would you consider tagging releases and adding release notes? In the meantime, users have to look through https://github.com/vmprof/vmprof-python/commits to try to tease out what's changed when there's a new release.

Here is an example of maintaining release notes alongside each release: https://github.com/jab/bidict/releases

Check out https://github.com/blog/1547-release-your-software for a walkthrough of using this feature. 
GitHub makes this a really nice user experience.

Thanks for your consideration and for the great work on vmprof.

**Comment by fijal** [comment]
good point, thanks, will try!

**Comment by jab** [comment]
Great, thanks!

**Comment by mattip** [comment]
Closing. We now tag the releases. Creating more documentation is harder, PR welcome to get the ball rolling.
