### ISSUE TITLE
Line-by-line profiling?

### ISSUE THREAD

**Issue by anntzer** [vmprof/vmprof-python#54]
It is possible to introspect the current line number in a CPython frame (`f_lineno`), and recording this information can obviously help the optimization of large-ish functions (see https://github.com/rkern/line_profiler for an instrumenting profiler with the same approach).

Any chance this capability can be added to vmprof? (crossposted as bdarnell/plop#27)

**Comment by planrich** [comment]
This has been contributed by @traff and is in the source tree for quite some time.
