### ISSUE TITLE
Segmentation fault using PyPy using pyglet

### ISSUE THREAD

**Issue by traff** [vmprof/vmprof-python#57]
1) Use the latest pypy built from sources
2) Try to profile the project https://github.com/fogleman/Minecraft

=>

/Users/traff/Projects/Minecraft/my-pypy-env/site-packages/vmprof-0.2.5-py2.7.egg/vmprof/__init__.py:39: RuntimeWarning: Using _continuation/greenlet/stacklet together with vmprof will crash
  _vmprof.enable(fileno, period)
Segmentation fault: 11

**Comment by traff** [comment]
Seems to be a know problem for vmprof and PyPy: https://mail.python.org/pipermail/pypy-commit/2016-January/095295.html

**Comment by fijal** [comment]
Does it use greenlets?

**Comment by fijal** [comment]
Works for me, tell me which OS X are you using and if the pypy that you translated is a recent one

**Comment by fijal** [comment]
I'm closing this one as I'm unable to reproduce as well as some of the problems has been fixed on OS X
