### ISSUE TITLE
'Python stopped working' error dialog while profiling on Windows

### ISSUE THREAD

**Issue by traff** [vmprof/vmprof-python#58]
I am running vmprof to profile tests of Pydev.Debugger project:

https://github.com/traff/PyDev.Debugger

I use Python 2.7.11 virtualenv with the latest(0.2.5) version of vmprof install.

I execute tests using this commandline:
`set PYTHONPATH=C:\Projects\PyDev.Debugger`
`python.exe -m vmprof tests_python\test_debugger.py`

After a while I have an error dialog(see on screenshot) and the process terminates.

![python-stopped-working](https://cloud.githubusercontent.com/assets/1814841/13354054/b2e55e8e-dc98-11e5-853e-e73c77a2f98e.png)

**Comment by fijal** [comment]
Reproduced

**Comment by fijal** [comment]
This one seems to be fixed (and succeeds)
