### ISSUE TITLE
Hides errors thrown by the profiled program

### ISSUE THREAD

**Issue by tehasdf** [vmprof/vmprof-python#6]
If the profiled program throws an error, vmprof never shows it to the user (and then the CLI crashes due to #1 because a script that errored out is too short to be profiled).
It seems that in `vmprof/__main__.py:main`:
```python
    try:
        sys.argv = [args.program] + args.args
        runpy.run_path(args.program, run_name='__main__')
    finally:
        vmprof.disable()
        show_stats(prof_file.name, output_mode, args)
```
you can simply have an `except:` with some logging

**Comment by fijal** [comment]
fixed
