### ISSUE TITLE
Running from terminal with -O produces no stats

### ISSUE THREAD

**Issue by maxfischer2781** [vmprof/vmprof-python#68]
I've been trying to benchmark an application with optimizations triggered by python's `-O` flag [1]. In this case, `vmprof` does not generate output unless an output file is set via `-o` as well. This breaks printing to the terminal and, worse, the `--web` option.
Tested with python 2.7 and 3.4, vmprof `0.2.7`.

I can reliably replicate using this program as `simple.py`:

```
#!/usr/bin/python
print(__debug__)

def foo():
    pass

for _ in range(int(1E5)):
    foo()
```

And calling `vmprof` from the command line:

```
$ python -O -m vmprof simple.py
False
no stats
```

```
$ python -m vmprof simple.py
True
 vmprof output:
 %:      name:                location:
 100.0%  _run_code            /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py:62
 100.0%  <module>             simple.py:2
 100.0%  _run_module_as_main  /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py:136
 100.0%  <module>             /usr/local/lib/python2.7/site-packages/vmprof/__main__.py:1
 100.0%  run_path             /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py:223
 100.0%  _run_module_code     /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py:75
 100.0%  main                 /usr/local/lib/python2.7/site-packages/vmprof/__main__.py:37
```

[1]
The `__debug__` constant, actually.

**Comment by maxfischer2781** [comment]
Some more information: This bug seems to appear whenever ``__debug__ == True``. It doesn't matter whether ``__debug__`` is set via the command line option ``-O`` or the environment variable ``PYTHONOPTIMIZE``.

**Comment by planrich** [comment]
The byte code optimizer manages to optimize away the full loop. So printing the message 'no stats' is legit in this case.

```
>>> import simple
>>> import dis
>>> dis.dis(simple)
Disassembly of foo:
  4           0 LOAD_CONST               0 (None)
              3 RETURN_VALUE
```

Can you verify if it still does not work on a larger program?

**Comment by maxfischer2781** [comment]
Sorry for the late reply, did not receive a notification.

This seems to work properly in a newer release
