### ISSUE TITLE
Installation broken on Fedora because other lib structures

### ISSUE THREAD

**Issue by pigmej** [vmprof/vmprof-python#7]
On fedora after installing libdwarf-devel (and other from family), libdwarf.h and dwarf.h are located in `/usr/include/libdwarf` not in `/usr/include/`, so the installation crashes:
`src/hotpatch/elf.c:9:19: fatal error: dwarf.h: No such file or directory`

After copying both files level up, then it crashes:
```src/hotpatch/elf.c:15:25: fatal error: libelf/gelf.h: No such file or directory```
`gelf.h` is NOT in subdirectory, copying file to `libelf` subdir solves the problem.

below are packages contents
```
$ rpm -ql libdwarf-devel-20150115-1.fc21.x86_64
/usr/include/libdwarf
/usr/include/libdwarf/dwarf.h
/usr/include/libdwarf/libdwarf.h
/usr/lib64/libdwarf.so
```

```
$ rpm -ql elfutils-libelf-devel.x86_64         
/usr/include/gelf.h
/usr/include/libelf.h
/usr/include/nlist.h
/usr/lib64/libelf.so
```

**Comment by fijal** [comment]
vmprof no longer depends on those libraries, closing
