### ISSUE TITLE
Confusing default period.

### ISSUE THREAD

**Issue by methane** [vmprof/vmprof-python#76]
The doc says:
> vmprof.enable(fileno, period=0.099, memory=False) - enable writing vmprof data to a file described by a fileno file descriptor. Timeout is in float seconds. The minimal available resolution is 4ms, we’re working on improving that (note the default is 9.9ms).
> https://vmprof.readthedocs.io/en/latest/#module-level-functions

0.099sec = 99ms, not 9.9ms.

And code is (`vmprof/__init__.py`):

```py
# it's not a good idea to use a "round" default sampling period, else we risk
# to oversample periodic tasks which happens to run at e.g. 100Hz or 1000Hz:
# http://www.solarisinternals.com/wiki/index.php/DTrace_Topics_Hints_Tips#profile-1001.2C_profile-997.3F
#
# To avoid the problem, we use a period which is "almost" but not exactly
# 1000Hz
DEFAULT_PERIOD = 0.00099
```

0.00099 = 0.99ms ?

**Comment by fijal** [comment]
yes, it should be "almost 1ms", not "almost 10ms"

**Comment by methane** [comment]
0.99ms < 4ms.
What about "The minimal available resolution is 4ms, "?

**Comment by fijal** [comment]
it's likely "around 1ms" but we never know for sure
