### ISSUE TITLE
Show time spent in CFFI/CPyExt as well

### ISSUE THREAD

**Issue by thedrow** [vmprof/vmprof-python#78]
It'd be nice to also get the symbols but even 'unknown' would be an improvement.
This uses CFFI: http://vmprof.com/#/0ab2bfc75156a4212cdb15954a6c0130
I expected to see the calls to C and how much time it takes to C to call Python again (using callbacks).
Instead I got 70% interpreted which doesn't seem right since most of the time this function spends is in C.

**Comment by planrich** [comment]
Starting from 0.4.0 (to be released soon) this will be possible. See the docs for more info.
