### ISSUE TITLE
<unknown code>  <unknown> when copying vmprof log while it is being written

### ISSUE THREAD

**Issue by lopuhin** [vmprof/vmprof-python#83]
If I have a process that is writing the vmprof log, and copy the log file to be able to see the current profiling information without stopping the process, the log does not contain source information: http://vmprof.com/#/6b1f680490d6ac2d2adb41859a510718, and ``vmprofshow`` displays most lines as ``X%  <unknown code>  X%  <unknown>``. If I stop the process then the source information is displayed correctly. I can reproduce it on CPython 3.4 and 3.5 on OS X and Ubuntu.

Is it a bug, or I need to stop the process to get full profile information?

**Comment by fijal** [comment]
Hi Kostia.

There are solutions to the issue, but I'm not completely sure if any of them are very good. One option is to call _vmprof.write_all_code_objects just after vmprof.enable(). That shold make it go away

**Comment by lopuhin** [comment]
Hi Maciej!
I tried calling _vmprof.write_all_code_objects, there are less ``<unkown>``s in the output, but there are still some left (probably because not all code is imported at the time I call it).
The full logs turned out to be too big anyway, so now I enable/disable vmprof manually by sending signals to the process and writing profiling logs to ``name-1.vmprof``, ``name-2.vmprof``, etc., and the problem went away, cause now I properly finish the profiler.

vmprof is great, thanks a lot!

**Comment by jonashaag** [comment]
@lopuhon consider https://github.com/vmprof/vmprof-python/pull/71#issuecomment-225684805 ;)
